field: 7f11b693-69b8-4a48-add0-ab165ca30b51 # CTA Blok
fieldLayouts:
  4cc091e1-af31-4ab5-92d7-71aff111ec5a:
    tabs:
      -
        elements:
          -
            fieldUid: 1a575702-f45e-4138-8d46-600cbcb5ad1d # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: be435e35-0b66-464c-b123-7a0f7022e428 # Intro
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a658cb99-0d95-4a8a-9a19-86b2f328d9a4 # CTA
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1a575702-f45e-4138-8d46-600cbcb5ad1d: # Titel
    contentColumnType: text
    fieldGroup: null
    handle: titel
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a658cb99-0d95-4a8a-9a19-86b2f328d9a4: # CTA
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: ''
    name: CTA
    searchable: false
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames: '*'
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\cta\fields\CTAField
  be435e35-0b66-464c-b123-7a0f7022e428: # Intro
    contentColumnType: text
    fieldGroup: null
    handle: intro
    instructions: ''
    name: Intro
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: ctaBlok
name: 'CTA Blok'
sortOrder: 1
