contentColumnType: boolean
fieldGroup: c454a233-b093-42df-9623-e466fed410f0 # Walk Detail
handle: switchGroup
instructions: 'Is dit een wandeling om enkel in groep te doen?'
name: 'Switch Group'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
